site_name: Next Gen Crypto Exchange
theme:
  name: 'material'
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Restful API Docs: rest-api.html
    - WebSockets API Docs: ws.md
    - Benchmarks: benchmarks.md
